apiVersion: v1
kind: Pod
metadata:
  name: podposixshm 
spec:
  restartPolicy : Never
  containers:
    - name: sender
      image: abcdesktopio/ipctest
      command: [ "/src/posix/shmem/memwriter" ]
    - name: receiver
      image: abcdesktopio/ipctest
      command: [  "/src/posix/shmem/memreader" ]
