apiVersion: v1
kind: Pod
metadata:
  name: podsysvsendershmtest
spec:
  shareProcessNamespace: true
  restartPolicy : Never
  volumes:
    - name: shared 
      emptyDir: {}
  containers:
    - name: sender
      image: abcdesktopio/ipctest
      command: [ "/bin/sleep", "1d" ]
      volumeMounts:
      - name: shared
        mountPath: /shared
      env:
      - name: FTOK_PATH
        value: "/shared/me"
    - name: receiver
      image: abcdesktopio/ipctest
      command: [ "/bin/sleep", "1d" ]
      volumeMounts:
      - name: shared
        mountPath: /shared
      env:
      - name: FTOK_PATH
        value: "/shared/me"
